Add Google Sign In
CodeForAfricaLabs/CitizenReporter.Android pull request #13
Opened 2017-09-05 15:27 UTC by Jeffkungu

#### What does this PR do?
Allows users to sign in using their Google accounts
#### Description of Task to be completed?
Add google Login to the app
#### How should this be manually tested?
After cloning the repo:
- Run the app in android studio
- Try Login in using Gmail

2017-09-05 15:46 UTC, phillipahereza commented
@Jeffkungu We can't have 3 different activities for logging in, all login has to be in one activity. There's no way around that

2017-09-05 15:52 UTC, Jeffkungu commented
I had a feeling about that, I had to get a confirmation thats why I sent the PR as early.

2017-09-05 15:54 UTC, phillipahereza commented
@Jeffkungu I don't think there's any app in the world that has Facebook and Google login on different activities 😕

2017-09-06 05:39 UTC, Jeffkungu commented
@phillipahereza Thank you, I'm still learning this basic conventions. I was trying out something and I needed to get your thoughts on it. I will send a better implementation of the same by end of day.

2017-09-07 12:01 UTC, phillipahereza requested changes
Basics Jeff, Basics!! 😕

2017-09-07 12:01 UTC, phillipahereza commented on app/src/main/java/org/codeforafrica/citizenreporterandroid/ui/auth/LoginActivity.java
> +    Name = (TextView)findViewById(R.id.google_user_name);
Variable names should *ALWAYS* start with lowercase letter

2017-09-07 12:12 UTC, Jeffkungu commented
Sorry about that, I have rectified it. won't happen again.

2017-09-07 19:32 UTC, phillipahereza approved these changes

2017-09-07 21:32 UTC, merged